### ISSUE TITLE
Please help verify that this is more correct than the previous beta

### ISSUE THREAD

**Issue by natefoo** [natefoo/galaxy-beta2#1]
Useless Former-commit-id is gone, as is all of the annoying '--HG--' changes to commit messages. The hg commit id of old commits is now stored in namespaced notes on those commits, which you can grab after cloning with `git fetch origin refs/notes/hg2git:refs/notes/hg2git` and display with `git log --show-notes=hg2git`. I like this better than using the default namespace for a few reasons:
1. The notes add about 8 MB to the repo size, and you don't get them with a default clone (whereas if they were in the default namespace, they would be included in the clone).
2. Notes in the default namespace show up with `git log` where you probably don't care about them, notes in a namespace requires you to explicitly add `--show-notes=`.

The only thing I'm not happy about is the fact that all of the commits from the beta1 version that I reapplied show me as the committer (the original authors still appear as the authors, thankfully). I didn't see a way to change that when using `git am` (the commits were exported from beta1 using `git format-patch`, maybe there is a better way).

Annoying everyone who I think might be interested in looking at this (people who showed interest in the creation of beta1): @blankenberg @dannon @erasche @jmchilton @jxtx @martenson @nsoranzo

If you take a look at this repo, please comment here and +1 if it looks good to you. If there aren't any problems identified by tomorrow or Monday, I'll nuke https://github.com/galaxyproject/galaxy/ and replace it with this.

**Comment by dannon** [comment]
+1

**Comment by hexylena** [comment]
+1 looks good!

"The only thing I'm not happy about is the fact that all of the commits
from the beta1 version that I reapplied show me as the committer"

That's fine IMO. Committing on behalf of someone else is perfectly
acceptable in this scenario since git tracked the authorship correctly.
(It's a practice I really like, especially for things like security patches
which are emailed and not PR'd. I'd _much_ rather see the commits with
their true author and a signed off on/committed by devteam, than just
having names in changelogs.)
21. feb. 2015 20.39 skrev "Dannon Baker" notifications@github.com:

**Comment by martenson** [comment]
works well for me, notes added ~10MB and mapping seems precise on few random changesets I have chosen, init files present

:+1:

**Comment by nsoranzo** [comment]
Git commit 9202f7fce593cf815e8b7a591c200f0a4708ff04 is missing from galaxy-central , the rest looks good!

Is .hgtags going to be removed again from the git repo? Or will this cause problems on hg side?

**Comment by natefoo** [comment]
I am running the git->hg script manually, and probably ran last before 9202f7f was committed. .hgtags will be removed again in a subsequent commit, I had to leave that commit out when reapplying from beta1 since all of the hg hashes changed, so the patch would not apply.

**Comment by jmchilton** [comment]
You mentioned in IRC that there would be no way to automatically back port fixes to the older releases in this repo to the bitbucket one. If that is the case I don't think we should be tracking that stuff here - we should just make those fixes in bitbucket directly - apply the same patch here to `15.03` and forward - and proceed normally. Those old tags are confusing enough to update without adding another complete set of taggy/branchy things to update with no automated process to keep things in sync. Am I wrong?

**Comment by natefoo** [comment]
I think we can backport, we'll just need to open release branches in hg. Also, we're not trying to manage hg tags here, we want them removed from git entirely. Or did I misunderstand you?

**Comment by nsoranzo** [comment]
@natefoo I mentioned that commit specifically because newer commits have been already added to galaxy-central, so I am suspecting some problem in the git->hg script.

**Comment by nsoranzo** [comment]
I see galaxy-central has been fixed, +1 now!

**Comment by natefoo** [comment]
Thanks for the help, all. I think we are ready to take it out of beta.
